# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

url: ""
baseurl: ""

# Site settings
title: Robotics Club IIITDM
email: robotics@iiitdm.ac.in
description: "The official website of Robotics Club Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram."


# Team names, titles and social links
people:
- name: [Jawahar]
  pic: 1
  position: CS Lead
  social:
    - title: instagram
      url: https://www.instagram.com/__juzzt__jawa__/
    - title: linkedin
      url: https://www.linkedin.com/in/jawahar-a-s-198084252/
    - title: github
      url: https://github.com/juzztjawa

- name: [Thulashitharan]
  pic: 2
  position: Core
  social:
    - title: instagram
      url: https://www.instagram.com/thulashitharan_/
    - title: linkedin
      url: https://www.linkedin.com/in/thulashitharan-d-460172228
    - title: user
      url: https://supernovatux.github.io/
    - title: github
      url: https://github.com/Supernovatux

- name: [Srikrishnan]
  pic: 3
  position: Mech Lead
  social:
    - title: instagram
      url: https://www.instagram.com/scraisk
    - title: linkedin
      url: https://www.linkedin.com/in/srikrishnan-srinivasan-672971189


- name: [Sakthiprian]
  pic: 4
  position: Senior co-ordinator
  social:
    - title: instagram
      url: https://www.instagram.com/sakthiprian/
    - title: linkedin
      url: https://www.linkedin.com/in/sakthiprian-s-3272a9240/
    - title: github
      url: https://github.com/Sakthiprian

- name: [Vedhava Krishna]
  pic: 5
  position: Co-ordinator
  social:
    - title: instagram
      url: https://www.instagram.com/yng.vedha_k
    - title: linkedin
      url: https://www.linkedin.com/in/k-r-vedhava-krishna-7a425a250/

- name: [Prahlad]
  pic: 6
  position: Co-ordinator
  social:
    - title: instagram
      url: https://www.instagram.com/p_r_a_h_l_a_d_1284/
    - title: linkedin
      url: https://www.linkedin.com/in/sridatta-prahlad-boddepalli-215576250/

- name: [Kalaiyarasan]
  pic: 7
  position: Co-ordinator
  social:
    - title: instagram
      url: https://www.instagram.com/kalai0452
    - title: linkedin
      url: https://www.linkedin.com/in/s-kalaiyarasan-b8476a21b/
    - title: github
      url: https://github.com/kalai0452

- name: [Aakash Madhu]
  pic: 8
  position: Co-ordinator
  social:
    - title: instagram
      url: https://www.instagram.com/aakash_madhu_s/
    - title: linkedin
      url: https://www.linkedin.com/in/aakash-madhu-60869b261
    - title: github
      url: https://github.com/Therriaakash

- name: [Nuaim]
  pic: 10
  position: Co-ordinator
  social:
    - title: instagram
      url: https://www.instagram.com/ace_falcon._/
    - title: linkedin
      url: https://www.linkedin.com/in/nuaim-mohammed-c-l-78532626a/
    - title: github
      url: https://github.com/Talentedfalcon

- name: [Mayank]
  pic: 11
  position: Alumni
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mayank-navneet-mehta/
    - title: github
      url: https://github.com/meetm473

- name: [Utkarsh]
  pic: 12
  position: Alumni
  social:
    - title: user
      url: https://utkarshverma.me/
    - title: github
      url: https://github.com/UtkarshVerma
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/roboticsclub.iiitdm/
  - title: linkedin
    url: https://www.linkedin.com/company/robotics-club-iiitdm-kancheepuram/
  - title: github
    url: https://github.com/Robotics-IIITDM

collections:
  blogs:
    output: true
    sort_by: date

# Postal address (add as many lines as necessary)
address:
  - line: D6, Pems Block, IIITDM
  - line: Melakottaiyur, Nellikuppam Rd, Near Kandigai, Off Vandalur-Kelambakkam Road
  - line: Chennai, Vengadamangalam, Tamil Nadu 600127

# Build settings
markdown: kramdown
permalink: pretty
google_analytics: G-0SZ4MSB60N
